### ISSUE TITLE
Cocoapods升级到1.0+以后 使用了此库依赖的pod库验证无法通过

### ISSUE THREAD

**Issue by aelam** [iException/BXTencentOpenAPI#1]
我个人的分享库中引用了此dependency, 然而再验证的过程中出现了 
    - NOTE  | [iOS] xcodebuild:  /Users/jenkins/Desktop/components/emsocialkit-ios/EMSocialKit/Share/QQ/EMActivityQQ.m:10:9: fatal error: 'TencentOpenAPI/TencentOAuth.h' file not found

之前在0.39.0的时候头文件是可以查找到的. 升级到1.0+以后不知道为什么无法使用了

**Comment by yimingtang** [comment]
😢  抱歉，才看到这个 issue。现在应该没问题了吧？！
